//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSrviceTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="printRequest", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class printRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string companyNameFieldField;
        
        private string embAliasFieldField;
        
        private string embossedNameFieldField;
        
        private System.DateTime expDateFieldField;
        
        private string firstNameFieldField;
        
        private string pANFieldField;
        
        private string pinIPFieldField;
        
        private string productIdFieldField;
        
        private string secondNameFieldField;
        
        private int seqNumFieldField;
        
        private System.DateTime startDateFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string companyNameField {
            get {
                return this.companyNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameFieldField, value) != true)) {
                    this.companyNameFieldField = value;
                    this.RaisePropertyChanged("companyNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string embAliasField {
            get {
                return this.embAliasFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.embAliasFieldField, value) != true)) {
                    this.embAliasFieldField = value;
                    this.RaisePropertyChanged("embAliasField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string embossedNameField {
            get {
                return this.embossedNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.embossedNameFieldField, value) != true)) {
                    this.embossedNameFieldField = value;
                    this.RaisePropertyChanged("embossedNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime expDateField {
            get {
                return this.expDateFieldField;
            }
            set {
                if ((this.expDateFieldField.Equals(value) != true)) {
                    this.expDateFieldField = value;
                    this.RaisePropertyChanged("expDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firstNameField {
            get {
                return this.firstNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameFieldField, value) != true)) {
                    this.firstNameFieldField = value;
                    this.RaisePropertyChanged("firstNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pANField {
            get {
                return this.pANFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pANFieldField, value) != true)) {
                    this.pANFieldField = value;
                    this.RaisePropertyChanged("pANField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pinIPField {
            get {
                return this.pinIPFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pinIPFieldField, value) != true)) {
                    this.pinIPFieldField = value;
                    this.RaisePropertyChanged("pinIPField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productIdField {
            get {
                return this.productIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.productIdFieldField, value) != true)) {
                    this.productIdFieldField = value;
                    this.RaisePropertyChanged("productIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string secondNameField {
            get {
                return this.secondNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.secondNameFieldField, value) != true)) {
                    this.secondNameFieldField = value;
                    this.RaisePropertyChanged("secondNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int seqNumField {
            get {
                return this.seqNumFieldField;
            }
            set {
                if ((this.seqNumFieldField.Equals(value) != true)) {
                    this.seqNumFieldField = value;
                    this.RaisePropertyChanged("seqNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime startDateField {
            get {
                return this.startDateFieldField;
            }
            set {
                if ((this.startDateFieldField.Equals(value) != true)) {
                    this.startDateFieldField = value;
                    this.RaisePropertyChanged("startDateField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="printResponse", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class printResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int statusFieldField;
        
        private string uIIDFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusField {
            get {
                return this.statusFieldField;
            }
            set {
                if ((this.statusFieldField.Equals(value) != true)) {
                    this.statusFieldField = value;
                    this.RaisePropertyChanged("statusField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uIIDField {
            get {
                return this.uIIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.uIIDFieldField, value) != true)) {
                    this.uIIDFieldField = value;
                    this.RaisePropertyChanged("uIIDField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="checkRequest", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class checkRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string uIIDFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uIIDField {
            get {
                return this.uIIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.uIIDFieldField, value) != true)) {
                    this.uIIDFieldField = value;
                    this.RaisePropertyChanged("uIIDField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="checkResponse", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class checkResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int statusFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusField {
            get {
                return this.statusFieldField;
            }
            set {
                if ((this.statusFieldField.Equals(value) != true)) {
                    this.statusFieldField = value;
                    this.RaisePropertyChanged("statusField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="closeRequest", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class closeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string uIIDFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uIIDField {
            get {
                return this.uIIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.uIIDFieldField, value) != true)) {
                    this.uIIDFieldField = value;
                    this.RaisePropertyChanged("uIIDField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="closeResponse", Namespace="http://schemas.datacontract.org/2004/07/CwHubWebService")]
    [System.SerializableAttribute()]
    public partial class closeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int statusFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusField {
            get {
                return this.statusFieldField;
            }
            set {
                if ((this.statusFieldField.Equals(value) != true)) {
                    this.statusFieldField = value;
                    this.RaisePropertyChanged("statusField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBindingInterface")]
    public interface IBindingInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/print", ReplyAction="http://tempuri.org/IBindingInterface/printResponse")]
        WebSrviceTest.ServiceReference1.printResponse print(WebSrviceTest.ServiceReference1.printRequest printRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/print", ReplyAction="http://tempuri.org/IBindingInterface/printResponse")]
        System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.printResponse> printAsync(WebSrviceTest.ServiceReference1.printRequest printRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/check", ReplyAction="http://tempuri.org/IBindingInterface/checkResponse")]
        WebSrviceTest.ServiceReference1.checkResponse check(WebSrviceTest.ServiceReference1.checkRequest checkRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/check", ReplyAction="http://tempuri.org/IBindingInterface/checkResponse")]
        System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.checkResponse> checkAsync(WebSrviceTest.ServiceReference1.checkRequest checkRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/close", ReplyAction="http://tempuri.org/IBindingInterface/closeResponse")]
        WebSrviceTest.ServiceReference1.closeResponse close(WebSrviceTest.ServiceReference1.closeRequest closeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBindingInterface/close", ReplyAction="http://tempuri.org/IBindingInterface/closeResponse")]
        System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.closeResponse> closeAsync(WebSrviceTest.ServiceReference1.closeRequest closeRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBindingInterfaceChannel : WebSrviceTest.ServiceReference1.IBindingInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BindingInterfaceClient : System.ServiceModel.ClientBase<WebSrviceTest.ServiceReference1.IBindingInterface>, WebSrviceTest.ServiceReference1.IBindingInterface {
        
        public BindingInterfaceClient() {
        }
        
        public BindingInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BindingInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BindingInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BindingInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebSrviceTest.ServiceReference1.printResponse print(WebSrviceTest.ServiceReference1.printRequest printRequest) {
            return base.Channel.print(printRequest);
        }
        
        public System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.printResponse> printAsync(WebSrviceTest.ServiceReference1.printRequest printRequest) {
            return base.Channel.printAsync(printRequest);
        }
        
        public WebSrviceTest.ServiceReference1.checkResponse check(WebSrviceTest.ServiceReference1.checkRequest checkRequest) {
            return base.Channel.check(checkRequest);
        }
        
        public System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.checkResponse> checkAsync(WebSrviceTest.ServiceReference1.checkRequest checkRequest) {
            return base.Channel.checkAsync(checkRequest);
        }
        
        public WebSrviceTest.ServiceReference1.closeResponse close(WebSrviceTest.ServiceReference1.closeRequest closeRequest) {
            return base.Channel.close(closeRequest);
        }
        
        public System.Threading.Tasks.Task<WebSrviceTest.ServiceReference1.closeResponse> closeAsync(WebSrviceTest.ServiceReference1.closeRequest closeRequest) {
            return base.Channel.closeAsync(closeRequest);
        }
    }
}
