//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace CwHubWebService
{
    //создание класса из wsdl
    //C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64>wsdl /out:src /sharetypes FILE:///CardKB.wsdl /serverinterface

    // 
    // Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
    // 
    /// <remarks/>
    [ServiceContract(Namespace = "urn:kubankredit:cardkb")]
    public interface IBindingInterface
    {
        /// <remarks/>
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        printResponse print(printRequest printRequest);

        /// <remarks/>
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        checkResponse check(checkRequest checkRequest);

        /// <remarks/>
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        closeResponse close(closeRequest closeRequest);
    }
    public partial class printRequest
    {

        private string PAN;

        private int seqNum;

        private string firstName;

        private string secondName;

        private string embossedName;

        private string companyName;

        private System.DateTime expDate;

        private System.DateTime startDate;

        private string productId;

        private string pinIP;

        private string embAlias;

        private string divisionName;
        
        public string Pan
        {
            get
            {
                return this.PAN;
            }
            set
            {
                this.PAN = value;
            }
        }

        public int SeqNum
        {
            get
            {
                return this.seqNum;
            }
            set
            {
                this.seqNum = value;
            }
        }

        public string FirstName
        {
            get
            {
                return this.firstName;
            }
            set
            {
                this.firstName = value;
            }
        }

        public string SecondName
        {
            get
            {
                return this.secondName;
            }
            set
            {
                this.secondName = value;
            }
        }

        public string EmbossedName
        {
            get
            {
                return this.embossedName;
            }
            set
            {
                this.embossedName = value;
            }
        }

        public string CompanyName
        {
            get
            {
                return this.companyName;
            }
            set
            {
                this.companyName = value;
            }
        }

        public System.DateTime ExpDate
        {
            get
            {
                return this.expDate;
            }
            set
            {
                this.expDate = value;
            }
        }

        public System.DateTime StartDate
        {
            get
            {
                return this.startDate;
            }
            set
            {
                this.startDate = value;
            }
        }

        public string ProductId
        {
            get
            {
                return this.productId;
            }
            set
            {
                this.productId = value;
            }
        }

        public string PinIP
        {
            get
            {
                return this.pinIP;
            }
            set
            {
                this.pinIP = value;
            }
        }

        public string EmbAlias
        {
            get
            {
                return this.embAlias;
            }
            set
            {
                this.embAlias = value;
            }
        }
        public string DivisionName
        {
            get
            {
                return this.divisionName;
            }
            set
            {
                this.divisionName = value;
            }
        }
    }

    public partial class printResponse
    {
        private string UIID;

        private int status;

        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }

        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }

    public partial class checkRequest
    {

        private string UIID;

        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }
    }

    public partial class checkResponse
    {

        private int status;

        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }

    public partial class closeRequest
    {

        private string UIID;

        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }
    }

    public partial class closeResponse
    {

        private int status;

        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }

    public partial class errorResponse
    {
        private int errCode;
        private string errText;
        public int ErrCode
        {
            get
            {
                return this.errCode;
            }
            set
            {
                this.errCode = value;
            }
        }
        public string ErrText
        {
            get
            {
                return this.errText;
            }
            set
            {
                this.errText = value;
            }
        }
    }
}