//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.ServiceModel;

namespace CwHubWebService
{
    //создание класса из wsdl
    //C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64>wsdl /out:src /sharetypes FILE:///CardKB.wsdl /serverinterface

    // 
    // Этот исходный код был создан с помощью wsdl, версия=4.6.1055.0.
    // 
    /// <remarks/>
    [ServiceContract(Namespace = "urn:kubankredit:cardkb")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BindingInterface", Namespace = "urn:kubankredit:cardkb")]
    public interface IBindingInterface
    {
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("print", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("printResponse", Namespace = "urn:kubankredit:cardkb")]
        printResponse print([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:kubankredit:cardkb")] printRequest printRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("check", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkResponse", Namespace = "urn:kubankredit:cardkb")]
        checkResponse check([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:kubankredit:cardkb")] checkRequest checkRequest);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [OperationContract]
        [FaultContract(typeof(errorResponse))]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("close", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("closeResponse", Namespace = "urn:kubankredit:cardkb")]
        closeResponse close([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:kubankredit:cardkb")] closeRequest closeRequest);
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class printRequest
    {

        private string PAN;

        private int seqNum;

        private string firstName;

        private string secondName;

        private string embossedName;

        private string companyName;

        private System.DateTime expDate;

        private System.DateTime startDate;

        private string productId;

        private string pinIP;

        private string embAlias;

        private string divisionName;

        /// <remarks/>
        public string Pan
        {
            get
            {
                return this.PAN;
            }
            set
            {
                this.PAN = value;
            }
        }

        /// <remarks/>
        public int SeqNum
        {
            get
            {
                return this.seqNum;
            }
            set
            {
                this.seqNum = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstName;
            }
            set
            {
                this.firstName = value;
            }
        }

        /// <remarks/>
        public string SecondName
        {
            get
            {
                return this.secondName;
            }
            set
            {
                this.secondName = value;
            }
        }

        /// <remarks/>
        public string EmbossedName
        {
            get
            {
                return this.embossedName;
            }
            set
            {
                this.embossedName = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyName;
            }
            set
            {
                this.companyName = value;
            }
        }

        /// <remarks/>
        public System.DateTime ExpDate
        {
            get
            {
                return this.expDate;
            }
            set
            {
                this.expDate = value;
            }
        }

        /// <remarks/>
        public System.DateTime StartDate
        {
            get
            {
                return this.startDate;
            }
            set
            {
                this.startDate = value;
            }
        }

        /// <remarks/>
        public string ProductId
        {
            get
            {
                return this.productId;
            }
            set
            {
                this.productId = value;
            }
        }

        /// <remarks/>
        public string PinIP
        {
            get
            {
                return this.pinIP;
            }
            set
            {
                this.pinIP = value;
            }
        }

        /// <remarks/>
        public string EmbAlias
        {
            get
            {
                return this.embAlias;
            }
            set
            {
                this.embAlias = value;
            }
        }
        public string DivisionName
        {
            get
            {
                return this.divisionName;
            }
            set
            {
                this.divisionName = value;
            }
        }

    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class printResponse
    {
        private string UIID;

        private int status;

        /// <remarks/>
        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class checkRequest
    {

        private string UIID;

        /// <remarks/>
        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class checkResponse
    {

        private int status;

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class closeRequest
    {

        private string UIID;

        /// <remarks/>
        public string uIID
        {
            get
            {
                return this.UIID;
            }
            set
            {
                this.UIID = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class closeResponse
    {

        private int status;

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Runtime.Serialization.DataContract()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:kubankredit:cardkb")]
    public partial class errorResponse
    {
        private int errCode;
        private string errText;
        public int ErrCode
        {
            get
            {
                return this.errCode;
            }
            set
            {
                this.errCode = value;
            }
        }
        public string ErrText
        {
            get
            {
                return this.errText;
            }
            set
            {
                this.errText = value;
            }
        }
    }
}